### ISSUE TITLE
Initial Designs

### ISSUE THREAD

**Issue by briancbarrow** [FreeCodeCamp-SLC/react-booklist#2]

**Comment by stevenCsaunders** [comment]
![Desktop Sign In](https://user-images.githubusercontent.com/28748240/108893706-a19bff00-75ce-11eb-92d7-56a0daf54bdf.jpg)
![Mobile Sign In](https://user-images.githubusercontent.com/28748240/108893710-a2cd2c00-75ce-11eb-8fb0-3de319e7cf40.jpg)
![Books](https://user-images.githubusercontent.com/28748240/108893725-a6f94980-75ce-11eb-9aab-6abc095587aa.jpg)
![Desktop Books](https://user-images.githubusercontent.com/28748240/108893728-a791e000-75ce-11eb-84c1-a81ecacf60d1.jpg)
![Mobile Nav Books](https://user-images.githubusercontent.com/28748240/108893731-a82a7680-75ce-11eb-81ec-886d6b934501.jpg)
![Desktop Form](https://user-images.githubusercontent.com/28748240/108893740-ab256700-75ce-11eb-8872-734d7c966d8f.jpg)
![Mobile Form](https://user-images.githubusercontent.com/28748240/108893741-ab256700-75ce-11eb-8cde-e42b913753aa.jpg)
![Mobile Menu](https://user-images.githubusercontent.com/28748240/108893744-ab256700-75ce-11eb-83e7-30ed8b6ee3af.jpg)
