### ISSUE TITLE
Fix books.map is not a function error.

### ISSUE THREAD

**Issue by AlexanderPuhl** [FreeCodeCamp-SLC/react-booklist#31]
To resolve this issue, we need a conditional to either render out something else if the books state is empty, something like "Loading..." or just a message saying "No books". There might be a better way to solve this as well that doesn't include conditional rendering.

**Comment by AlexanderPuhl** [comment]
https://www.robinwieruch.de/react-hooks-fetch-data

This link could be useful to find a proper way of handling this.

**Comment by AlexanderPuhl** [comment]
https://reactjs.org/docs/concurrent-mode-suspense.html

If we want to, we could also check out this experimental feature which could be dangerous.

**Comment by erikhiggy** [comment]
I'll take it

**Comment by briancbarrow** [comment]
> I'll take it

Hi @erikhiggy thanks for being willing. This project is for people in our local study group to get experience writing code in a more 'real' setting. We're going to keep it for them for the time being. Hope that makes sense.

**Comment by AlexanderPuhl** [comment]
I don't realize adding the "Help Wanted" tag was broadcasting to the world, sorry about the confusion @erikhiggy .

**Comment by dustin-lamarr** [comment]
I can start working on it today
