### ISSUE TITLE
Add icons to the dashboard navigation links

### ISSUE THREAD

**Issue by zorro1rr** [FreeCodeCamp-SLC/react-booklist#39]
The dashboard navigation links for both mobile and desktop needs icons.

We are using https://heroicons.com/ for our icons. Grab one that looks like the design and add it to the project. You can use the Add Book link as an example of how to do it.

![dashboard icon](https://user-images.githubusercontent.com/50159035/121796053-59cbd280-cbd3-11eb-8dd0-da677235a9f6.png)
![dashboard icon2](https://user-images.githubusercontent.com/50159035/121796291-12464600-cbd5-11eb-9d9d-7e4b504414fa.png)

**Comment by soham4abc** [comment]
I can work on this issue! If possible pls assign!
