### ISSUE TITLE
On the dashboard, get the image of the book from google API to populate the img element

### ISSUE THREAD

**Issue by AlexanderPuhl** [FreeCodeCamp-SLC/react-booklist#4]
The image URL should already be coming in from the Google books API, we just need to grab the value and populate the image element so that we can see the individual book images on the dashboard.

![image](https://user-images.githubusercontent.com/22256166/140006165-8d99d73c-c8ee-47f5-91f5-004ee21b2f37.png)

**Comment by Ovorp** [comment]
I have a PR for this issue.  I'm just testing it to make sure there are no issues and then I can create a PR for it.
