### ISSUE TITLE
Create a route and navigation links for the favorites page

### ISSUE THREAD

**Issue by zorro1rr** [FreeCodeCamp-SLC/react-booklist#40]
Make a new route for the favorites page and hook it up to navigation links for both mobile and desktop.

You don't have to build out the favorites page yet, a simple component rendering something like "favorites page" is fine.

![favorites](https://user-images.githubusercontent.com/50159035/121796559-20956180-cbd7-11eb-9b8c-1b8979059728.png)

**Comment by tusharb05** [comment]
Should I try this? I am just a beginner in React.js but I know react-router-dom

**Comment by AlexanderPuhl** [comment]
Merged the pull request.
