### ISSUE TITLE
Rework login page to work with Auth0

### ISSUE THREAD

**Issue by AlexanderPuhl** [FreeCodeCamp-SLC/react-booklist#43]
Basically just have a login button.

**Comment by stevenCsaunders** [comment]
Here is the preview of the single sign in/sign up button on the login page. I'll get this implemented in the next day or so.

![Frame 1](https://user-images.githubusercontent.com/28748240/125678294-fa40a323-426d-4a9d-835e-59a834a96ae3.jpg)
![Frame 2](https://user-images.githubusercontent.com/28748240/125678301-ea985129-10c4-4c56-92a6-3c31dc9d9bdc.jpg)
