### ISSUE TITLE
The favorites should be a heart icon in the upper right corner.

### ISSUE THREAD

**Issue by AlexanderPuhl** [FreeCodeCamp-SLC/react-booklist#53]
![image](https://user-images.githubusercontent.com/22256166/181135584-07331c48-e318-4fef-bc83-8fd9cdd782d1.png)

The favorites feature is working, but it just displays true/false on the book card. We would like this to be a heart icon in the upper right corner that is either filled out or not.

**Comment by zorro1rr** [comment]
Let's do a gray heart that is unfilled for unfavorited books and a red filled-in heart for favorited books.
