### ISSUE TITLE
Add the side "Header" to the profile page

### ISSUE THREAD

**Issue by AlexanderPuhl** [FreeCodeCamp-SLC/react-booklist#56]
![image](https://user-images.githubusercontent.com/22256166/181404445-a47bb55b-96e0-48d9-91af-d743e95a37cf.png)

The side "header" outlined in red in the picture is missing from the profile page, we'd like to add that.

**Comment by mcoreycoder** [comment]
I was able to get this addressed.

**Comment by mcoreycoder** [comment]
I also added a link to the Profile icon in the upper right to take you to the profile page.

**Comment by mcoreycoder** [comment]
This has been merged, the issue can be closed.
