### ISSUE TITLE
Next and Previous arrows don't work on the first click

### ISSUE THREAD

**Issue by AlexanderPuhl** [FreeCodeCamp-SLC/react-booklist#57]
![image](https://user-images.githubusercontent.com/22256166/181404519-fb91d0a1-c923-4d67-b05a-4920cd7c2fd6.png)

![image](https://user-images.githubusercontent.com/22256166/181404559-7f7fa7be-17d5-4a3f-b063-8e8215e1d285.png)

It takes two clicks to get the next / previous arrows to respond.

**Comment by mcoreycoder** [comment]
arrows fixed, issue relted to order of opperation, post increment/decrement was not passing correct value, pre increment/decrement resolved issue, closes #57
