### ISSUE TITLE
Center the pagination

### ISSUE THREAD

**Issue by AlexanderPuhl** [FreeCodeCamp-SLC/react-booklist#58]
![image](https://user-images.githubusercontent.com/22256166/181404623-2476c72b-0269-4f9f-aa77-ca7a7878a422.png)

Currently the pagination is aligned to the left, It would look nice if it was centered.

**Comment by mcoreycoder** [comment]
I have been able to get this issue resolved and center the Pagination.

**Comment by mcoreycoder** [comment]
This has been merged, the issue can be closed.
