### ISSUE TITLE
When adding a book from a list, the list dropdown should have the list already selected.

### ISSUE THREAD

**Issue by AlexanderPuhl** [FreeCodeCamp-SLC/react-booklist#59]
![image](https://user-images.githubusercontent.com/22256166/183550877-6333c1ee-39af-4ae1-95af-d87acfcc46ba.png)

When we click on the "add book" button shown above, it should send the list id to the AddBook component.

![image](https://user-images.githubusercontent.com/22256166/183551692-3634ed70-e26a-4317-b8c1-77111a27ae19.png)

We want the list dropdown circled in the second picture to already have the correct list selected.

**Comment by mcoreycoder** [comment]
I have been working on this and came up with a solution for this issue. Not exactly what was requested here but I think you will like it.
