### ISSUE TITLE
Design Login Screen

### ISSUE THREAD

**Issue by davdaarn** [FreeCodeCamp-SLC/react-booklist#6]
As a developer I should markup and style a login page.
The login page should be responsive and styled to resemble the images below.

![image](https://user-images.githubusercontent.com/5161103/108932400-28b49b80-75fe-11eb-8614-0340cd9cca01.png)

![image](https://user-images.githubusercontent.com/5161103/108932459-4550d380-75fe-11eb-91b7-7071cf0f7d8a.png)

**Comment by AlexanderPuhl** [comment]
Gonna close this issue since we already have an issue for this.
