### ISSUE TITLE
Update text on delete list modal from "collection" to "list"

### ISSUE THREAD

**Issue by zorro1rr** [FreeCodeCamp-SLC/react-booklist#63]
The text on the delete list modal/button says "collection" several times. We were calling the "lists" "collections" for awhile, but we decided to use "lists" instead. Update the text in those 4 places on the modal/button

![image](https://user-images.githubusercontent.com/50159035/184509936-27b23a6f-0122-4fb0-9cc7-af246b5b3bba.png)

**Comment by fjuren** [comment]
Hi I can work on this one.
