### ISSUE TITLE
Style the landing page.

### ISSUE THREAD

**Issue by AlexanderPuhl** [FreeCodeCamp-SLC/react-booklist#9]
Use the Landing.js file for this. We want to have the login and registration options on this page instead of being on separate pages. Instead of having a Login.js and Registration.js in the pages folder w/ a link to them in the Header. Lets move these files into the components folder and then import them into the Landing.js file.

Remember to use mobile first methodology, meaning the default style is for the mobile screens and then you modify the styling as the screen gets bigger.

We also want to show the login component by default, but add a button for new users that will swap out the login component for the registration component.

For now we don't need the "Start your 14-day free trial" text or the signing in w/ social media options.

![image](https://user-images.githubusercontent.com/22256166/109746973-8c593e80-7b93-11eb-96e6-60b6cb682eac.png)

![image](https://user-images.githubusercontent.com/28748240/108893706-a19bff00-75ce-11eb-92d7-56a0daf54bdf.jpg)

**Comment by stevenCsaunders** [comment]
Removed unneeded elements from login design.

![Frame 1](https://user-images.githubusercontent.com/28748240/110211063-0b7b9a80-7e52-11eb-8165-248aca06df64.jpg)
![Frame 2](https://user-images.githubusercontent.com/28748240/110211066-0f0f2180-7e52-11eb-98d1-dff440609323.jpg)

**Comment by stevenCsaunders** [comment]
Updated Design to remove unneeded elements.
![Frame 1](https://user-images.githubusercontent.com/28748240/110211602-9493d100-7e54-11eb-8ba9-5de448aed12a.jpg)
![Frame 2](https://user-images.githubusercontent.com/28748240/110211606-952c6780-7e54-11eb-98a0-23d0f8880052.jpg)
